### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by v1talii-dev** [maoberlehner/distributed-vue-applications-loading-components-via-http#7]
I use the `externalComponent` [function](https://github.com/maoberlehner/distributed-vue-applications-loading-components-via-http/blob/b01b3bf84b4244bd8caac2806780643f926b1078/src/utils/external-component.js#L1) on vue-router pages. When I switch between pages, the elements are not cleared from the window object, and this leads to memory leaks, as a result of which our application crashes with the error "out of memory". I tried manually clearing `window[name] = null`, but it doesn't affect anything, and in the developer tools I still see that the destroyed components refer to an area in memory. Has anyone noticed such problems? You can check through the separated elements tool https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks

**Comment by v1talii-dev** [comment]
@maoberlehner Can you please comment on this situation?

**Comment by maoberlehner** [comment]
Maybe you can try something like:

```js
(await window[name]).$destroy();
delete window[name];
```

As a sidenote: this code was written before Module Federation became a thing. If you have the chance, I highly recommend you looking into it: https://webpack.js.org/concepts/module-federation/

**Comment by v1talii-dev** [comment]
`window[name]` contains an object, that is, the result of the compiled library. This object does not have a `$destroy` method. If you use module federation, how can this be combined with this approach? For example, for an application that has a plugin system, where a plugin is a compiled library from vue components. At the same time, these components are loaded via api and mounted in the SPA on the fly (using your approach).

**Comment by maoberlehner** [comment]
It is impossible for me to say what's preventing the object from the library from being garbage collected. So I don't think I can help you with that.

With Module Federation you don't need my approach anymore. Module Federation is a standardized approach to loading code from and sharing code with remote resources. I can't think of anything that you can do with my approach that you can't with module federation. So if you have problems using my approach I highly recommend you look into Module Federation. If Module Federation had existed at that time, I'd never had written this article.
